### PR TITLE
fix(sys): compile mimalloc as C++ on windows-msvc targets

### LINKED ISSUE #64: `libmimalloc-sys2 0.1.55` fails to build on `aarch64-pc-windows-msvc` with clang: undeclared `__ldar64` / `__stlr64`
## Summary

Building `libmimalloc-sys2 0.1.55` for the `aarch64-pc-windows-msvc` target with `clang` as the C compiler fails because the bundled `mimalloc/include/mimalloc/atomic.h` calls the MSVC ARM64 intrinsics `__ldar64` and `__stlr64` without a declaration that clang can see. The same setup worked on `0.1.54`, so this is a regression introduced in `0.1.55`.

The downstream `mimalloc-safe` crate, when resolved to a version whose `libmimalloc-sys2` constraint admits `0.1.55`, breaks the aarch64-pc-windows-msvc release build for any project using `TARGET_CC=clang`.

## Environment

- Crate: `libmimalloc-sys2 = 0.1.55`
- Parent crate: `mimalloc-safe` (latest at the time of the failure; the failing project pinned `mimalloc-safe = "=0.1.58"` and still hit this because its `libmimalloc-sys2` requirement allowed 0.1.55)
- Target triple: `aarch64-pc-windows-msvc`
- Host: GitHub Actions `windows-2025` runner (Windows Server 2025 Datacenter, 10.0.26100)
- `TARGET_CC=clang`
- Rust: stable (release build via `napi build --target aarch64-pc-windows-msvc --release`)

## Reproduction

In a workspace whose `Cargo.toml` depends on `mimalloc-safe` (any version that resolves `libmimalloc-sys2 = 0.1.55`):

```sh
# On a Windows runner with clang available
set TARGET_CC=clang
cargo build --release --target aarch64-pc-windows-msvc
```

Minimal reproduction is available in the rolldown CI failure log:

- Failing run: https://github.com/rolldown/rolldown/actions/runs/25723489236/job/75533705378
- Mitigation PRs (workarounds, not upstream fixes):
  - https://github.com/rolldown/rolldown/pull/9361 — pin `mimalloc-safe` to `=0.1.58`
  - https://github.com/rolldown/rolldown/pull/9372 — additionally pin `libmimalloc-sys2` to `=0.1.54` via `Cargo.lock`
- Same regression reported in oxc: https://github.com/oxc-project/oxc/pull/22329

## Error output

```
   Compiling libmimalloc-sys2 v0.1.55
warning: libmimalloc-sys2@0.1.55: In file included from ./c_src/mimalloc/src/static.c:17:
warning: libmimalloc-sys2@0.1.55: In file included from ./c_src/mimalloc/include\mimalloc/internal.h:16:
warning: libmimalloc-sys2@0.1.55: In file included from ./c_src/mimalloc/include\mimalloc\types.h:29:
warning: libmimalloc-sys2@0.1.55: ./c_src/mimalloc/include\mimalloc\atomic.h:230:14: error: call to undeclared function '__ldar64'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
warning: libmimalloc-sys2@0.1.55:   230 |       return MI_MSC_XX(__ldar)((volatile const uintptr_t*)p);
warning: libmimalloc-sys2@0.1.55:       |              ^
warning: libmimalloc-sys2@0.1.55: ./c_src/mimalloc/include\mimalloc\atomic.h:164:23: note: expanded from macro 'MI_MSC_XX'
warning: libmimalloc-sys2@0.1.55:   164 | #define MI_MSC_XX(f)  f##64
warning: libmimalloc-sys2@0.1.55:       |                       ^
warning: libmimalloc-sys2@0.1.55: <scratch space>:9:1: note: expanded from here
warning: libmimalloc-sys2@0.1.55:     9 | __ldar64
warning: libmimalloc-sys2@0.1.55:       | ^
warning: libmimalloc-sys2@0.1.55: ./c_src/mimalloc/include\mimalloc\atomic.h:252:7: error: call to undeclared function '__stlr64'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
warning: libmimalloc-sys2@0.1.55:   252 |       MI_MSC_XX(__stlr)((volatile uintptr_t*)p,x);
warning: libmimalloc-sys2@0.1.55:       |       ^
warning: libmimalloc-sys2@0.1.55: ./c_src/mimalloc/include\mimalloc\atomic.h:273:14: error: call to undeclared function '__ldar64'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
warning: libmimalloc-sys2@0.1.55:   273 |       return __ldar64((volatile const uintptr_t*)p);
warning: libmimalloc-sys2@0.1.55:       |              ^
warning: libmimalloc-sys2@0.1.55: ./c_src/mimalloc/include\mimalloc\atomic.h:298:7: error: call to undeclared function '__stlr64'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
warning: libmimalloc-sys2@0.1.55:   298 |       __stlr64((volatile uint64_t*)p, (uint64_t)x);
warning: libmimalloc-sys2@0.1.55:       |       ^
warning: libmimalloc-sys2@0.1.55: 4 errors generated.
error: failed to run custom build command for `libmimalloc-sys2 v0.1.55`
```

## Analysis

`atomic.h` in the bundled mimalloc sources uses `__ldar64` / `__stlr64` through the `MI_MSC_XX` macro. These are MSVC-specific ARM64 load-acquire / store-release intrinsics (declared in MSVC's `<intrin.h>` / `<arm64intr.h>`). When the file is compiled by `clang` targeting `aarch64-pc-windows-msvc`, these intrinsics are not visible, so clang reports `call to undeclared function`. Under newer clang defaults this is an error rather than a warning, which fails the build.

`0.1.54` did not exhibit this, so the regression is in whatever change `0.1.55` made (likely a bump of the bundled mimalloc C source, or a change to the include/guard layout).

Possible fixes (one of):

1. Guard the affected branches so they are only compiled under MSVC (`#if defined(_MSC_VER) && !defined(__clang__)`), and fall back to the `__atomic_*` / inline-asm path under clang on Windows-ARM64.
2. Forward-declare or include the MSVC intrinsic headers (`<intrin.h>`) when targeting Windows-ARM64, including under clang-cl / clang.
3. Yank `0.1.55` and re-release a fixed `0.1.56` so consumers that don't carry an explicit pin recover automatically.

## Workaround for downstream users

Pin `libmimalloc-sys2` to `=0.1.54` in `Cargo.lock`:

```sh
cargo update -p libmimalloc-sys2 --precise 0.1.54
```

(Pinning `mimalloc-safe` alone is not sufficient — its version requirement still allows `libmimalloc-sys2 0.1.55` to be resolved.)

### PR DESCRIPTION
**Pull request by shulaoda**
Fixes #64

## Summary

Force `libmimalloc-sys/c_src/mimalloc/src/static.c` to be compiled as C++ on every windows-msvc target, not just MSVC-style drivers. This fixes the `aarch64-pc-windows-msvc` build under `TARGET_CC=clang` and aligns the post-#16 `cc-rs` path with the pre-#16 `cmake` path, which explicitly set `MI_USE_CXX=ON`.

## Why

Since `libmimalloc-sys2 0.1.55` bumped the bundled mimalloc submodule, `aarch64-pc-windows-msvc` builds invoked with `TARGET_CC=clang` fail:

```
./c_src/mimalloc/include/mimalloc/atomic.h:230:14: error: call to undeclared function '__ldar64'
./c_src/mimalloc/include/mimalloc/atomic.h:252:7:  error: call to undeclared function '__stlr64'
./c_src/mimalloc/include/mimalloc/atomic.h:273:14: error: call to undeclared function '__ldar64'
./c_src/mimalloc/include/mimalloc/atomic.h:298:7:  error: call to undeclared function '__stlr64'
error: failed to run custom build command for `libmimalloc-sys2 v0.1.55`
```

Failing CI run (rolldown): https://github.com/rolldown/rolldown/actions/runs/25723489236/job/75533705378

Same regression reported in oxc: https://github.com/oxc-project/oxc/pull/22329

### Root cause

`atomic.h` has three mutually exclusive branches:

```c
#if defined(__cplusplus)            // <atomic> path (always safe)
#elif defined(_MSC_VER)             // MSVC plain-C wrapper using MSVC intrinsics
#else                               // C11 <stdatomic.h> path
```

- clang invoked as `clang --target=*-pc-windows-msvc` defines `_MSC_VER` for MSVC ABI compatibility, so when the source is compiled as C it takes the `_MSC_VER` branch.
- The `_M_ARM64` sub-branch of that path calls `__ldar64` / `__stlr64`, which are MSVC-only intrinsics. clang does not declare them in C mode on Windows, hence the build failure.
- Upstream mimalloc explicitly recommends *"always compile as C++ when using MSVC"* and uses `set_source_files_properties(... LANGUAGE CXX)` in its own `CMakeLists.txt` to enforce this. Compiling as C++ takes the `#if defined(__cplusplus)` branch and avoids the MSVC-intrinsics path entirely.

### Why the previous code did not already do this

`build_mimalloc_win` was introduced in #16, replacing a `cmake` path that explicitly set `MI_USE_CXX=ON`. The intent was preserved as:

```rust
.cpp(false)
...
if build.get_compiler().is_like_msvc() {
    build.cpp(true);
}
```

However `cc::Build::cpp(true)` does **not** inject `/TP` or `-x c++` (a search of `cc-1.2.x` confirms this) — it only changes which env vars are read (`CXX` / `CXXFLAGS`), the compiler binary name resolution (`clang` → `clang++`, `gcc` → `g++`), and C++ stdlib linking. `cl.exe` still compiles `static.c` as C, and `clang++` dispatches by extension and also compiles `.c` as C. So `MI_USE_CXX=ON` was never actually re-implemented after the `cmake` → `cc-rs` migration; the bug was masked by coincidence:

| Compiler              | Arch    | Branch taken | Why it worked                                                  |
| --------------------- | ------- | ------------ | -------------------------------------------------------------- |
| `cl.exe`              | x64     | `_M_X64`     | uses portable `__iso_volatile_load64` etc.                     |
| `cl.exe`              | aarch64 | `_M_ARM64`   | cl declares `__ldar64` / `__stlr64` natively                   |
| `clang` (msvc target) | x64     | `_M_X64`     | clang also declares `__iso_volatile_load64`                    |
| `clang` (msvc target) | aarch64 | `_M_ARM64`   | **clang does not declare `__ldar64` / `__stlr64`** → fails     |

The recent mimalloc submodule bump made the `_M_ARM64` sub-branch the only path that matters on ARM64, exposing the coincidence.

## Fix

Explicitly force C++ compilation of `static.c` regardless of driver:

```rust
if build.get_compiler().is_like_msvc() {
    build.flag("/TP");
} else {
    build.flag("-xc++");
}
```

`cpp(true)` is still kept so `CXX` / C++ stdlib resolution behave correctly. `/TP` covers `cl.exe` and `clang-cl.exe`; `-xc++` covers plain `clang.exe` (gnu-driver) with `--target=*-pc-windows-msvc`.

This restores the original `MI_USE_CXX=ON` semantics that #16 intended to carry over.

## Related

Downstream pin workarounds (can be reverted once this lands and a new `libmimalloc-sys2` is published):

- rolldown/rolldown#9361 — pin `mimalloc-safe = "=0.1.58"`
- rolldown/rolldown#9372 — pin `libmimalloc-sys2 = "=0.1.54"` in `Cargo.lock`
- oxc-project/oxc#22329 — same regression

### CODE REVIEW

**Comment by shulaoda** [comment]
Test in https://github.com/rolldown/rolldown/pull/9373
